# Generated by Django 5.0.4 on 2024-05-22 08:22

import django.db.models.deletion
import ramen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=3)),
                ('primary_color', models.CharField(max_length=7, validators=[ramen.models.validate_hex_color])),
                ('secondary_color', models.CharField(max_length=7, validators=[ramen.models.validate_hex_color])),
                ('team_name', models.CharField(max_length=255)),
                ('funds', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramen.place')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('silenced', models.BooleanField(default=False)),
                ('ese', models.IntegerField()),
                ('money', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.discordchannel')),
                ('connections', models.ManyToManyField(blank=True, to='ramen.player')),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pronouns', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('alive', models.BooleanField(default=True)),
                ('hair_color', models.CharField(blank=True, max_length=255, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('injury_status', models.CharField(blank=True, max_length=255, null=True)),
                ('fav_color', models.CharField(max_length=7, validators=[ramen.models.validate_hex_color])),
                ('job', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('primary_weapon', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_weapon', models.CharField(blank=True, max_length=255, null=True)),
                ('mutations', models.TextField(blank=True, null=True)),
                ('pet', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ramen.dorm')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ramen.player')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ramen.place')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramen.character')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramen.subject')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_students', to='ramen.subject'),
        ),
        migrations.AddField(
            model_name='character',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_students', to='ramen.subject'),
        ),
    ]
