# Generated by Django 4.2.7 on 2023-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster', models.BooleanField(default=False)),
                ('discord_id', models.IntegerField()),
            ],
        ),
    ]
