# Generated by Django 5.0.4 on 2024-05-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('competitive', models.BooleanField(default=False)),
                ('max_length', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('boosts', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorantAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('smokes', models.BooleanField(blank=True, null=True)),
                ('blinds', models.BooleanField(blank=True, null=True)),
                ('scouts', models.BooleanField(blank=True, null=True)),
                ('flanks', models.BooleanField(blank=True, null=True)),
                ('duels', models.BooleanField(blank=True, null=True)),
                ('controls', models.BooleanField(blank=True, null=True)),
                ('initiates', models.BooleanField(blank=True, null=True)),
                ('sentinels', models.BooleanField(blank=True, null=True)),
                ('heals', models.BooleanField(blank=True, null=True)),
                ('stuns', models.BooleanField(blank=True, null=True)),
                ('aoe', models.BooleanField(blank=True, null=True)),
                ('walls', models.BooleanField(blank=True, null=True)),
                ('emoji', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntroSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('short', models.BooleanField(default=False)),
                ('generic', models.BooleanField(default=False)),
                ('length', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.discorduser')),
            ],
        ),
    ]
