# Generated by Django 4.2.7 on 2023-12-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('competitive', models.BooleanField(default=False)),
                ('max_length', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='booster',
        ),
        migrations.CreateModel(
            name='IntroSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField()),
                ('short', models.BooleanField(default=False)),
                ('generic', models.BooleanField(default=False)),
                ('length', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.discorduser')),
            ],
        ),
    ]
