# Generated by Django 5.0.4 on 2024-05-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
    ]
