# Generated by Django 5.0.4 on 2024-05-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_discorduser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsound',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
