# Generated by Django 5.1.3 on 2024-11-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_introsound_last_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='introsound',
            name='condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
